### ISSUE TITLE
One small issue...

### ISSUE THREAD

**Issue by donspaulding** [mirusresearch/vue-wysiwyg#1]
This seems to be written in Javascript.  Could you rewrite it in rust?  Rust is an up-and-coming language with lots to recommend it.  I've never written anything in it, but I think you should rewrite this project ASAP.

Good luck!

**Comment by vingiesel** [comment]
If Rust is so cool, why is there no Rust 2? Exactly, return to Go

**Comment by donspaulding** [comment]
No Rust 2 because they didn't bork the crate specification like godep.

**Comment by JohnmarkBeaty** [comment]
Rust also has a lot of cool frameworks like Rocket and stuff.
One that I think would be particularly useful in this case is `mongo_driver` https://crates.io/crates/mongo_driver check it out and let me know your thoughts.

**Comment by donspaulding** [comment]
@JohnmarkBeaty Hmm, that crate doesn't appear to target nightly though, so I'm not sure I would trust it.  Other than that, [at least MongoDB is web scale](https://www.youtube.com/watch?v=b2F-DItXtZs).
